### ISSUE TITLE
k8s.community integration/auth page is showing incorrect token

### ISSUE THREAD

**Issue by takama** [k8s-community/ui#12]
```yaml
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: https://master.k8s.community
      name: master-class
    contexts:
    - context:
        cluster: master-class
        user: master-class
      name: master-class
    current-context: master-class
    users:
    - name: master-class
      user:
        token: AfpXXXXXXXXXXXXXXXXXXXXX
```
